version: '3'

networks:
  wp-network:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wp-network
  db_wordpress:
    image: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: db_wordpress
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=WzD986fiWJoRuP
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=sc-paulosilva
      - MYSQL_PASSWORD=WzD986fiWJoRuP
    expose:
      - 3306
      - 33060
    networks:
      - wp-network
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db_wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: sc-paulosilva
      WORDPRESS_DB_PASSWORD: WzD986fiWJoRuP
    depends_on:
      - nginx
      - db_wordpress
    networks:
      - wp-network


volumes:
  db_data:
  wordpress_data:
